### ISSUE TITLE
ignore scss imports

### ISSUE THREAD

**Issue by teebszet** [meteortesting/meteor-mocha#42]
I have an issue with testing .jsx files which import .scss

directory-splash.jsx:

```
import React from 'react';                                                                                             
import PropTypes from 'prop-types';                                                                                    
import './directory-splash.scss';

export const DirectorySplash = ({backgroundImage, title}) => (                                                         
  (backgroundImage || title) ?
    <div className="directory-splash"                                                                                  
      style={backgroundImage ? {backgroundImage: `url(${backgroundImage})`} : null}                                    
    >
      <img className="directory-splash__image" src={backgroundImage} />                                                
      <h2 className="directory-splash__title">{title}</h2>                                                             
    </div> : null
);
DirectorySplash.propTypes = {
  backgroundImage: PropTypes.string,
  title: PropTypes.string,
};

export default DirectorySplash;
```

error output from meteor test:
```
W20170824-18:08:53.054(8)? (STDERR) Error: Cannot find module './directory-splash.scss'
W20170824-18:08:53.054(8)? (STDERR)     at makeMissingError (packages/modules-runtime.js:221:12)
W20170824-18:08:53.055(8)? (STDERR)     at require (packages/modules-runtime.js:231:19)
W20170824-18:08:53.055(8)? (STDERR)     at meteorInstall.imports.ui.components.directory-splash.directory-splash.jsx (imports/ui/components/directory-splash/directory-splash.jsx:1:210)
W20170824-18:08:53.055(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170824-18:08:53.055(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170824-18:08:53.056(8)? (STDERR)     at meteorInstall.imports.ui.components.directory-splash.directory-splash.test.js (imports/ui/components/directory-splash/directory-splash.test.js:1:258)
W20170824-18:08:53.056(8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:333:9)
W20170824-18:08:53.056(8)? (STDERR)     at require (packages/modules-runtime.js:228:16)
W20170824-18:08:53.057(8)? (STDERR)     at /private/var/folders/gk/7789rgc16wxbhv6tbw0tn7dh0000gr/T/meteor-test-run16w461j/.meteor/local/build/programs/server/app/app.js:14600:1
W20170824-18:08:53.057(8)? (STDERR)     at /private/var/folders/gk/7789rgc16wxbhv6tbw0tn7dh0000gr/T/meteor-test-run16w461j/.meteor/local/build/programs/server/boot.js:338:34
```

I wonder if there something similar to `mocha --require ignore-styles` - where ignore-styles is an npm package which skips imports of .scss files.

**Comment by aldeed** [comment]
Please submit this as a [meteor/meteor](https://github.com/meteor/meteor) issue
