### ISSUE TITLE
TypeError when using chrome driver

### ISSUE THREAD

**Issue by lorensr** [meteortesting/meteor-mocha#52]
Steps to reproduce:
- `meteor create app` (version 1.6.1)
- `meteor add meteortesting:mocha`
- `meteor npm i --save-dev selenium-webdriver chromedriver`

```
$  TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha 
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
I20180223-19:48:25.236(-5)?                   
I20180223-19:48:25.541(-5)? --------------------------------
I20180223-19:48:25.542(-5)? ----- RUNNING SERVER TESTS -----
I20180223-19:48:25.542(-5)? --------------------------------
I20180223-19:48:25.542(-5)? 
I20180223-19:48:25.542(-5)? 
I20180223-19:48:25.543(-5)? 
I20180223-19:48:25.543(-5)?   0 passing (1ms)
I20180223-19:48:25.543(-5)? 
I20180223-19:48:25.543(-5)? 
I20180223-19:48:25.543(-5)? --------------------------------
I20180223-19:48:25.543(-5)? ----- RUNNING CLIENT TESTS -----
I20180223-19:48:25.544(-5)? --------------------------------
W20180223-19:48:26.683(-5)? (STDERR) /Users/me/.meteor/packages/meteor-tool/.1.6.1.18y0axr.54yj++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180223-19:48:26.684(-5)? (STDERR)                                            throw(ex);
W20180223-19:48:26.684(-5)? (STDERR)                                            ^
W20180223-19:48:26.685(-5)? (STDERR) 
W20180223-19:48:26.685(-5)? (STDERR) TypeError: driver.manage(...).window(...).setPosition is not a function
W20180223-19:48:26.685(-5)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:45:28)
W20180223-19:48:26.685(-5)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:22:7)
W20180223-19:48:26.685(-5)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:120:3)
W20180223-19:48:26.686(-5)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:145:7)
W20180223-19:48:26.686(-5)? (STDERR)     at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:100:13)
W20180223-19:48:26.686(-5)? (STDERR)     at done (/Users/me/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.x96wd2++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:497:13)
W20180223-19:48:26.686(-5)? (STDERR)     at Runner.<anonymous> (/Users/me/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.x96wd2++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:804:5)
W20180223-19:48:26.687(-5)? (STDERR)     at emitNone (events.js:111:20)
W20180223-19:48:26.687(-5)? (STDERR)     at Runner.emit (events.js:208:7)
W20180223-19:48:26.687(-5)? (STDERR)     at /Users/me/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.x96wd2++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:791:12
W20180223-19:48:26.687(-5)? (STDERR)     at Runner.runSuite (/Users/me/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.x96wd2++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:589:12)
W20180223-19:48:26.688(-5)? (STDERR)     at start (/Users/me/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.x96wd2++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:789:10)
W20180223-19:48:26.688(-5)? (STDERR)     at Runner.run (/Users/me/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.x96wd2++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:816:5)
W20180223-19:48:26.688(-5)? (STDERR)     at Mocha.run (/Users/me/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.x96wd2++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:501:17)
W20180223-19:48:26.688(-5)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:98:17)
W20180223-19:48:26.689(-5)? (STDERR)     at Object.start (packages/meteortesting:mocha/server.js:144:5)
W20180223-19:48:26.689(-5)? (STDERR)     at packages/meteor.js:1107:27
W20180223-19:48:26.689(-5)? (STDERR)     at Function.time (/private/tmp/meteor-test-runreob4l.ntgdd/.meteor/local/build/programs/server/profile.js:309:28)
W20180223-19:48:26.689(-5)? (STDERR)     at /private/tmp/meteor-test-runreob4l.ntgdd/.meteor/local/build/programs/server/boot.js:427:13
W20180223-19:48:26.690(-5)? (STDERR)     at /private/tmp/meteor-test-runreob4l.ntgdd/.meteor/local/build/programs/server/boot.js:472:5
W20180223-19:48:26.690(-5)? (STDERR)     at Function.run (/private/tmp/meteor-test-runreob4l.ntgdd/.meteor/local/build/programs/server/profile.js:510:12)
W20180223-19:48:26.690(-5)? (STDERR)     at /private/tmp/meteor-test-runreob4l.ntgdd/.meteor/local/build/programs/server/boot.js:470:11
=> Started your app.

=> App running at: http://localhost:3000/
$
```

repro: https://github.com/lorensr/meteor-mocha-chrome-repro

**Comment by crapthings** [comment]
@lorensr any update?

**Comment by crapthings** [comment]
https://github.com/giggio/node-chromedriver/issues/142

**Comment by lorensr** [comment]
Pinning to these works:

```
    "chromedriver": "2.35.0",
    "selenium-webdriver": "3.6.0"
```

**Comment by SimonSimCity** [comment]
@lorensr which OS are you running on? Just for adding a cross-reference to https://github.com/meteortesting/meteor-mocha/issues/71#issuecomment-430936393

**Comment by lorensr** [comment]
`macOS 10.14.1`

**Comment by inspiraluna** [comment]
"chromedriver": "^2.44.0" also seems to work.
