### ISSUE TITLE
driver.manage(...).window(...).setPosition is not a function

### ISSUE THREAD

**Issue by crapthings** [meteortesting/meteor-mocha#54]
meteor 1.6.1

```
meteor create app --bare
```

```
# Meteor packages used by this project, one per line.
# Check this file (and the other files in this directory) into your repository.
#
# 'meteor add' and 'meteor remove' will edit this file for you,
# but you can also edit it by hand.

meteor-base@1.3.0             # Packages every Meteor app needs to have
mobile-experience@1.0.5       # Packages for a great mobile UX
mongo@1.4.2                   # The database Meteor supports right now
static-html             # Define static page content in .html files
reactive-var@1.0.11            # Reactive variable for tracker
tracker@1.1.3                 # Meteor's client-side reactive programming library

standard-minifier-css@1.4.0   # CSS minifier run for production mode
standard-minifier-js@2.3.1    # JS minifier run for production mode
es5-shim@4.7.0                # ECMAScript 5 compatibility for older browsers
ecmascript@0.10.0              # Enable ECMAScript2015+ syntax in app code
shell-server@0.3.1            # Server-side component of the `meteor shell` command
meteortesting:mocha
```

```
{
  "name": "meteor-test-and-ci",
  "private": true,
  "scripts": {
    "start": "meteor run",
    "test": "TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha",
    "test-dev": "TEST_WATCH=1 meteor test --driver-package meteortesting:mocha"
  },
  "dependencies": {
    "@babel/runtime": "^7.0.0-beta.36",
    "meteor-node-stubs": "^0.3.2"
  },
  "devDependencies": {
    "chai": "^4.1.2",
    "chromedriver": "^2.35.0",
    "selenium-webdriver": "^4.0.0-alpha.1"
  }
}
```

```
TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha
```

```
=> App running at: http://localhost:3000/
    ✓ should be true95(8)?
I20180227-15:36:58.495(8)?
I20180227-15:36:58.495(8)?
I20180227-15:36:58.495(8)?   1 passing (15ms)
I20180227-15:36:58.495(8)?
I20180227-15:36:58.495(8)?
I20180227-15:36:58.496(8)? --------------------------------
I20180227-15:36:58.496(8)? ----- RUNNING CLIENT TESTS -----
I20180227-15:36:58.496(8)? --------------------------------
W20180227-15:36:58.579(8)? (STDERR) meteor://💻app/packages/meteortesting_browser-tests.js:133
W20180227-15:36:58.579(8)? (STDERR)   driver.manage().window().setPosition(20000, 20000); // We periodically grab logs from Chrome and pass them back.
W20180227-15:36:58.580(8)? (STDERR)                            ^
W20180227-15:36:58.580(8)? (STDERR)
W20180227-15:36:58.580(8)? (STDERR) TypeError: driver.manage(...).window(...).setPosition is not a function
W20180227-15:36:58.580(8)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:45:28)
W20180227-15:36:58.580(8)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:22:7)
W20180227-15:36:58.581(8)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:120:3)
W20180227-15:36:58.581(8)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:145:7)
W20180227-15:36:58.581(8)? (STDERR)     at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:100:13)
W20180227-15:36:58.581(8)? (STDERR)     at done (/Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:497:13)
W20180227-15:36:58.581(8)? (STDERR)     at Runner.<anonymous> (/Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:804:5)
W20180227-15:36:58.582(8)? (STDERR)     at emitNone (events.js:111:20)
W20180227-15:36:58.582(8)? (STDERR)     at Runner.emit (events.js:208:7)
W20180227-15:36:58.582(8)? (STDERR)     at /Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:791:12
W20180227-15:36:58.582(8)? (STDERR)     at /Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:644:9
W20180227-15:36:58.582(8)? (STDERR)     at next (/Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:284:14)
W20180227-15:36:58.582(8)? (STDERR)     at Immediate._onImmediate (/Users/monsterstep/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.1eq52gt++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:320:5)
W20180227-15:36:58.583(8)? (STDERR)     at runCallback (timers.js:789:20)
W20180227-15:36:58.583(8)? (STDERR)     at tryOnImmediate (timers.js:751:5)
W20180227-15:36:58.583(8)? (STDERR)     at processImmediate [as _immediateCallback] (timers.js:722:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! meteor-test-and-ci@ test: `TEST_BROWSER_DRIVER=chrome meteor test --once --driver-package meteortesting:mocha`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meteor-test-and-ci@ test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/monsterstep/.npm/_logs/2018-02-27T07_36_58_731Z-debug.log
```

**Comment by crapthings** [comment]
https://github.com/meteortesting/meteor-mocha/issues/52

**Comment by crapthings** [comment]
it works after i downgrade the "selenium-webdriver"
"selenium-webdriver": "^3.6.0"

**Comment by crapthings** [comment]
https://github.com/giggio/node-chromedriver/issues/142
