### ISSUE TITLE
Error: Cannot find module 'chromedriver' while running test-packages

### ISSUE THREAD

**Issue by serut** [meteortesting/meteor-mocha#63]
Hey !

I tryed to use this library to run tests of [meteor-coverage](https://github.com/serut/meteor-coverage) but it looks like phantomjs can't do the job (can't write to global vars, dkw). I tryed to use chrome as a workaround but when I start the test, it fails on boot.

https://travis-ci.org/serut/meteor-coverage/builds/372737749

```
$ meteor npm test
> meteor-coverage@2.0.2 test /home/travis/build/serut/meteor-coverage
> TEST_BROWSER_DRIVER=chrome COVERAGE=1 COVERAGE_OUT_LCOVONLY=1 COVERAGE_APP_FOLDER=$PWD/ meteor test-packages --once --settings .coverage.json --driver-package meteortesting:mocha
[[[[[ Tests ]]]]]
=> Started proxy.
=> Started MongoDB.
W20180429-17:26:09.371(0)? (STDERR) No packages under test in test-packages mode
W20180429-17:26:09.416(0)? (STDERR) { Error: Cannot find module 'chromedriver'
W20180429-17:26:09.417(0)? (STDERR)     at Function.Module._resolveFilename (module.js:547:15)
W20180429-17:26:09.417(0)? (STDERR)     at Function.resolve (internal/module.js:18:19)
W20180429-17:26:09.418(0)? (STDERR)     at Object.require (/tmp/meteor-test-run6vr4jh.xaojc/.meteor/local/build/programs/server/boot.js:288:32)
W20180429-17:26:09.418(0)? (STDERR)     at makeInstallerOptions.fallback (packages/modules-runtime.js:651:18)
W20180429-17:26:09.418(0)? (STDERR)     at require (packages/modules-runtime.js:244:16)
W20180429-17:26:09.419(0)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:30:5)
W20180429-17:26:09.419(0)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:23:7)
W20180429-17:26:09.419(0)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:138:3)
W20180429-17:26:09.420(0)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:168:7)
W20180429-17:26:09.420(0)? (STDERR)     at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:118:13)
W20180429-17:26:09.421(0)? (STDERR)     at done (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:497:13)
W20180429-17:26:09.421(0)? (STDERR)     at Runner.<anonymous> (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:804:5)
W20180429-17:26:09.421(0)? (STDERR)     at emitNone (events.js:111:20)
W20180429-17:26:09.422(0)? (STDERR)     at Runner.emit (events.js:208:7)
W20180429-17:26:09.422(0)? (STDERR)     at /home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:791:12
W20180429-17:26:09.423(0)? (STDERR)     at Runner.runSuite (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:589:12) code: 'MODULE_NOT_FOUND' }
W20180429-17:26:09.423(0)? (STDERR) /home/travis/.meteor/packages/meteor-tool/.1.6.1_1.c76v6p.io9tw++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180429-17:26:09.423(0)? (STDERR) 						throw(ex);
W20180429-17:26:09.424(0)? (STDERR) 						^
W20180429-17:26:09.424(0)? (STDERR) 
W20180429-17:26:09.424(0)? (STDERR) Error: When running app tests with TEST_BROWSER_DRIVER=chrome, you must first "npm i --save-dev selenium-webdriver@3.0.0-beta-2 chromedriver"
W20180429-17:26:09.425(0)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:36:11)
W20180429-17:26:09.425(0)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:23:7)
W20180429-17:26:09.425(0)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:138:3)
W20180429-17:26:09.426(0)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:168:7)
W20180429-17:26:09.426(0)? (STDERR)     at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:118:13)
W20180429-17:26:09.427(0)? (STDERR)     at done (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:497:13)
W20180429-17:26:09.427(0)? (STDERR)     at Runner.<anonymous> (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:804:5)
W20180429-17:26:09.427(0)? (STDERR)     at emitNone (events.js:111:20)
W20180429-17:26:09.428(0)? (STDERR)     at Runner.emit (events.js:208:7)
W20180429-17:26:09.428(0)? (STDERR)     at /home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:791:12
W20180429-17:26:09.428(0)? (STDERR)     at Runner.runSuite (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:589:12)
W20180429-17:26:09.429(0)? (STDERR)     at start (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:789:10)
W20180429-17:26:09.429(0)? (STDERR)     at Runner.run (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:816:5)
W20180429-17:26:09.430(0)? (STDERR)     at Mocha.run (/home/travis/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.y1brx5.30jqo++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:501:17)
W20180429-17:26:09.430(0)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:111:17)
W20180429-17:26:09.430(0)? (STDERR)     at Object.start (packages/meteortesting:mocha/server.js:167:5)
I20180429-17:26:09.435(0)? 
I20180429-17:26:09.435(0)? --------------------------------
I20180429-17:26:09.436(0)? ----- RUNNING SERVER TESTS -----
I20180429-17:26:09.436(0)? --------------------------------
I20180429-17:26:09.436(0)? 
I20180429-17:26:09.436(0)? 
I20180429-17:26:09.437(0)? 
I20180429-17:26:09.437(0)?   0 passing (0ms)
I20180429-17:26:09.437(0)? 
I20180429-17:26:09.438(0)? 
I20180429-17:26:09.438(0)? --------------------------------
I20180429-17:26:09.438(0)? ----- RUNNING CLIENT TESTS -----
I20180429-17:26:09.438(0)? --------------------------------
=> Started your app.
=> App running at: http://localhost:3000/
npm ERR! Test failed.  See above for more details.
The command "meteor npm test" exited with 1.
```

The configuration : 
- `package.js`
```
Package.onTest(function (api) {
  api.use(['meteortesting:mocha']);
  Npm.depends({
    'chai': '2.1.0',
    'selenium-webdriver': '3.0.0-beta-2',
    'chromedriver': '2.38.2'
   });
```
- `package.json` 
```
"devDependencies": {
    "chromedriver": "^2.38.2",
    "selenium-webdriver": "3.0.0-beta-2"
  },
```

Any help would be much appreciated !

**Comment by serut** [comment]
Here is the workaround : 

```
"setup-test": "rm -rf ./someapp && meteor create --bare someapp && cd someapp && cp ../.coverage.json . && meteor npm i --save selenium-webdriver@3 chromedriver && mkdir packages && ln -s ../../ ./packages/meteor-coverage",
"test": "meteor npm run setup-test && cd someapp && TEST_BROWSER_DRIVER=chrome COVERAGE_VERBOSE=1 COVERAGE=1 COVERAGE_OUT_LCOVONLY=1 COVERAGE_APP_FOLDER=$(pwd)/ meteor test-packages --once --driver-package meteortesting:mocha ./packages/meteor-coverage",
```

It creates an empty app, then run tests from there.

**Comment by aldeed** [comment]
As it looks like you realized, this is [this Meteor issue](https://github.com/meteor/meteor/issues/8577)
