### ISSUE TITLE
Can't run client tests with Chrome on Unbuntu

### ISSUE THREAD

**Issue by eric-burel** [meteortesting/meteor-mocha#71]
Hi,
When running this command: `TEST_BROWSER_DRIVER=chrome TEST_WATCH=1 meteor test-packages ./packages/* --driver-package meteortesting:mocha --raw-logs`,
I get the error below. This seems to be a config issue when setting up the Chrome driver.

```
TypeError: options.toCapabilities is not a function
    at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:46:82)
    at startBrowser (packages/meteortesting:browser-tests/server.js:23:7)
    at clientTests (packages/meteortesting:mocha/server.js:138:3)
    at serverTests (packages/meteortesting:mocha/server.js:168:7)
    at mochaInstance.run.failureCount (packages/meteortesting:mocha/server.js:118:13)
    at done (/home/eric-burel/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.12nygdi.uqn4++os+web.browser+web.cordova/npm/node_modules/mocha/lib/mocha.js:497:13)
    at Runner.<anonymous> (/home/eric-burel/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.12nygdi.uqn4++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:804:5)
    at emitNone (events.js:111:20)
    at Runner.emit (events.js:208:7)
    at /home/eric-burel/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.12nygdi.uqn4++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:791:12
    at /home/eric-burel/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.12nygdi.uqn4++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:644:9
    at next (/home/eric-burel/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.12nygdi.uqn4++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:284:14)
    at Immediate._onImmediate (/home/eric-burel/.meteor/packages/practicalmeteor_mocha-core/.1.0.1.12nygdi.uqn4++os+web.browser+web.cordova/npm/node_modules/mocha/lib/runner.js:320:5)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by aldeed** [comment]
Maybe related to the fact that this package doesn't work with test-packages due to Meteor issue: https://github.com/meteor/meteor/issues/8577

**Comment by hexsprite** [comment]
Not sure if this helps but I'm using `TEST_BROWSER_DRIVER=chrome` on OSX with these versions:

```
"chromedriver": "^2.41.0",
"selenium-webdriver": "^3.6.0",
```

**Comment by DanielDornhardt** [comment]
Thx @hexsprite , "selenium-webdriver": "^3.6.0" did it for me.

**Comment by Nomeasmo** [comment]
I think you can close if the documentation is updated.

**Comment by SimonSimCity** [comment]
Thanks, I'm adding a cross-reference to https://github.com/meteortesting/meteor-mocha/issues/80
