### ISSUE TITLE
Error running package tests

### ISSUE THREAD

**Issue by namirsab** [meteortesting/meteor-mocha#77]
Suddenly I'm getting this error when running package tests:
```
W20180821-10:45:24.181(2)? (STDERR) The version of @babel/runtime installed in your node_modules directory 
W20180821-10:45:24.198(2)? (STDERR) (7.0.0-rc.1) contains a breaking change which was introduced by 
W20180821-10:45:24.199(2)? (STDERR) https://github.com/babel/babel/pull/8266. Please either downgrade by 
W20180821-10:45:24.199(2)? (STDERR) running the following command:
W20180821-10:45:24.199(2)? (STDERR) 
W20180821-10:45:24.199(2)? (STDERR)   meteor npm install --save-exact @babel/runtime@7.0.0-beta.55
W20180821-10:45:24.199(2)? (STDERR) 
W20180821-10:45:24.199(2)? (STDERR) or update to the latest beta version of Meteor 1.7.1, as explained in 
W20180821-10:45:24.200(2)? (STDERR) this pull request: https://github.com/meteor/meteor/pull/9942.
W20180821-10:45:24.200(2)? (STDERR) 
W20180821-10:45:24.200(2)? (STDERR) /tmp/meteor-test-run1sp8nu1.yyrk/.meteor/local/build/programs/server/boot.js:475
W20180821-10:45:24.200(2)? (STDERR) }).run();
W20180821-10:45:24.200(2)? (STDERR)    ^
W20180821-10:45:24.200(2)? (STDERR) 
W20180821-10:45:24.201(2)? (STDERR) Error: Cannot find module './defineProperty'
W20180821-10:45:24.201(2)? (STDERR)     at makeMissingError (packages/modules-runtime.js:231:12)
W20180821-10:45:24.201(2)? (STDERR)     at require (packages/modules-runtime.js:241:19)
W20180821-10:45:24.201(2)? (STDERR)     at objectSpread.js (packages/modules.js:504:22)
W20180821-10:45:24.201(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180821-10:45:24.201(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180821-10:45:24.201(2)? (STDERR)     at logging.js (/tmp/meteor-test-run1sp8nu1.yyrk/.meteor/local/build/programs/server/packages/logging.js:26:45)
W20180821-10:45:24.202(2)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180821-10:45:24.202(2)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180821-10:45:24.202(2)? (STDERR)     at /tmp/meteor-test-run1sp8nu1.yyrk/.meteor/local/build/programs/server/packages/logging.js:511:15
W20180821-10:45:24.202(2)? (STDERR)     at /tmp/meteor-test-run1sp8nu1.yyrk/.meteor/local/build/programs/server/packages/logging.js:518:3
``` 

I've tried doing what is there, but it does not help.

Does anybody know anything about this?

Thanks in advance

Meteor 1.6.1
meteortesting:mocha@1.0.1 (but it happens in every version)

**Comment by SimonSimCity** [comment]
What is the version of `@babel/runtime` you're asking for in your `packages.json` file - and which version do you actually have installed?

**Comment by SimonSimCity** [comment]
I'm closing this due to lack of feedback. It also seems like it's a meteor-related error, unrelated to this package.

**Comment by namirsab** [comment]
@SimonSimCity sorry for the delay, i didn't get the notification :sweat_smile: 
Just to clarify, we updated Meteor and it helped. It was probably a combination between babel and meteor, but the weird part is that it started happening out of sudden (probably some weird package-lock.json issues)
